MAX_SHEET_LENGTH = 5
MAX_CATEGORIES_SHEET_LENGTH = 5

LEFT_ARROW = "←"
RIGHT_ARROW = "→"
BACK_ARROW = "Назад"
ADD = "+"
EDIT = "✎"
DELETE = "❌"
SUBMIT = "✓︎"
CANCEL = "⨯"
CLOCK = "⏰"

MAIN_MENU_HANDLER = 0


PLACEMARK_INSERTER_LOCATION_HANDLER = 1
PLACEMARK_INSERTER_DESCRIPTION_HANDLER = 2
PLACEMARK_INSERTER_CATEGORIES_HANDLER = 3
PLACEMARK_INSERTER_TAGS_HANDLER = 4
PLACEMARK_INSERTER_INSERT_TAG_HANDLER = 5


EDIT_PLACEMARKS_PLACEMARK_SELECTOR_HANDLER = 6
EDIT_PLACEMARKS_HANDLER = 7
EDIT_PLACEMARKS_TAGS_HANDLER = 8
EDIT_PLACEMARKS_DESCRIPTION_HANDLER = 9
EDIT_PLACEMARKS_CATEGORIES_HANDLER = 10
EDIT_PLACEMARKS_LOCATION_HANDLER = 11
EDIT_PLACEMARKS_DELETE_HANDLER = 12
EDIT_PLACEMARKS_EDIT_MENU_HANDLER = 13
EDIT_PLACEMARKS_ADDRESS_HANDLER = 14
EDIT_PLACEMARKS_INSERT_TAG_HANDLER = 15


WEEKDAYS_HANDLER = 16
HOURS_HANDLER = 17


APPROVED_PLACEMARKS_HANDLER = 18
APPROVED_PLACEMARKS_PLACEMARK_INFO_HANDLER = 19


CATEGORIES_AND_TAGS_CATEGORIES_MENU_HANDLER = 20
CATEGORIES_AND_TAGS_INSERT_CATEGORY_MENU_HANDLER = 21
CATEGORIES_AND_TAGS_DELETE_CATEGORY_MENU_HANDLER = 22
CATEGORIES_AND_TAGS_EDIT_CATEGORY_MENU_HANDLER = 23
CATEGORIES_AND_TAGS_TAGS_MENU_HANDLER = 24
CATEGORIES_AND_TAGS_INSERT_TAG_MENU_HANDLER = 25
CATEGORIES_AND_TAGS_DELETE_TAG_MENU_HANDLER = 26
CATEGORIES_AND_TAGS_TAG_MENU_HANDLER = 27
CATEGORIES_AND_TAGS_EDIT_TAG_HANDLER = 28


NEW_PLACEMARKS_HANDLER = 29
NEW_PLACEMARKS_PLACEMARK_MENU_HANDLER = 30
NEW_PLACEMARKS_PLACEMARK_DELETE_HANDLER = 31
NEW_PLACEMARKS_PLACEMARK_APPROVE_HANDLER = 32
NEW_PLACEMARKS_PLACEMARK_EDIT_HANDLER = 33
NEW_PLACEMARKS_PLACEMARK_EDIT_DESCRIPTION_HANDLER = 34
NEW_PLACEMARKS_PLACEMARK_EDIT_GEOTAG_HANDLER = 35
NEW_PLACEMARKS_PLACEMARK_EDIT_ADDRESS_HANDLER = 36
NEW_PLACEMARKS_PLACEMARK_NEW_TAGS_HANDLER = 37
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_HANDLER = 38
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_EDIT_HANDLER = 39
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_DELETE_HANDLER = 40
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_APPROVE_HANDLER = 41

NOTIFICATION_HANDLER = 42
