MAX_SHEET_LENGTH = 5
MAX_CATEGORIES_SHEET_LENGTH = 5

LEFT_ARROW = "←"
RIGHT_ARROW = "→"
BACK_ARROW = "↵"
ADD = "+"
EDIT = "✎"
DELETE = "❌"
SUBMIT = "✓︎"
CANCEL = "⨯"

MAIN_MENU_HANDLER = 50

PLACEMARK_SELECTOR_HANDLER = 0

PLACEMARK_INSERTER_LOCATION_HANDLER = 1
PLACEMARK_INSERTER_DESCRIPTION_HANDLER = 2
PLACEMARK_INSERTER_CATEGORIES_HANDLER = 3
PLACEMARK_INSERTER_TAGS_HANDLER = 4
PLACEMARK_INSERTER_INSERT_TAG_HANDLER = 5

PLACEMARK_EDITOR_HANDLER = 6
PLACEMARK_EDITOR_TAGS_HANDLER = 7
PLACEMARK_EDITOR_DESCRIPTION_HANDLER = 8
PLACEMARK_EDITOR_CATEGORIES_HANDLER = 9
PLACEMARK_EDITOR_LOCATION_HANDLER = 10
PLACEMARK_EDITOR_DELETE_HANDLER = 12
PLACEMARK_EDITOR_EDIT_MENU_HANDLER = 13
PLACEMARK_EDITOR_ADDRESS_HANDLER = 14
PLACEMARK_EDITOR_INSERT_TAG_HANDLER = 15



MODE_SELECTOR_HANDLER = 16
NEW_TAGS_HANDLER = 17
APPROVED_PLACEMARKS_HANDLER = 18
ADD_CATEGORIES_AND_TAGS_HANDLER = 19
ADD_CATEGORY_HANDLER = 20
ADD_TAG_HANDLER = 21
APPROVED_PLACEMARKS_PLACEMARK_INFO_HANDLER = 22

INSERT_CATEGORY_AND_TAG_CATEGORIES_MENU_HANDLER = 23
INSERT_CATEGORY_AND_TAG_INSERT_CATEGORY_MENU_HANDLER = 24
INSERT_CATEGORY_AND_TAG_DELETE_CATEGORY_MENU_HANDLER = 25
INSERT_CATEGORY_AND_TAG_EDIT_CATEGORY_MENU_HANDLER = 26
INSERT_CATEGORY_AND_TAG_TAGS_MENU_HANDLER = 27
INSERT_CATEGORY_AND_TAG_INSERT_TAG_MENU_HANDLER = 28
INSERT_CATEGORY_AND_TAG_DELETE_TAG_MENU_HANDLER = 29
INSERT_CATEGORY_AND_TAG_TAG_MENU_HANDLER = 30
INSERT_CATEGORY_AND_TAG_EDIT_TAG_HANDLER = 31

NEW_TAGS_TAGS_MENU_HANDLER = 32
NEW_TAGS_TAG_MENU_HANDLER = 33
NEW_TAGS_TAG_EDIT_HANDLER = 34
NEW_TAGS_TAG_DELETE_HANDLER = 35
NEW_TAGS_TAG_APPROVE_HANDLER = 36

NEW_PLACEMARKS_HANDLER = 37
NEW_PLACEMARKS_PLACEMARK_MENU_HANDLER = 38
NEW_PLACEMARKS_PLACEMARK_DELETE_HANDLER = 39
NEW_PLACEMARKS_PLACEMARK_APPROVE_HANDLER = 40
NEW_PLACEMARKS_PLACEMARK_EDIT_HANDLER = 41
NEW_PLACEMARKS_PLACEMARK_EDIT_DESCRIPTION_HANDLER = 42
NEW_PLACEMARKS_PLACEMARK_EDIT_GEOTAG_HANDLER = 43
NEW_PLACEMARKS_PLACEMARK_EDIT_ADDRESS_HANDLER = 44
NEW_PLACEMARKS_PLACEMARK_NEW_TAGS_HANDLER = 45
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_HANDLER = 46
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_EDIT_HANDLER = 47
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_DELETE_HANDLER = 48
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_APPROVE_HANDLER = 49
