MAX_SHEET_LENGTH = 5
MAX_CATEGORIES_SHEET_LENGTH = 5

LEFT_ARROW = "←"
RIGHT_ARROW = "→"
BACK_ARROW = "↵"
ADD = "+"
EDIT = "✎"
DELETE = "❌"
SUBMIT = "✓︎"
CANCEL = "⨯"

PLACEMARK_SELECTOR_HANDLER = 0

PLACEMARK_INSERTER_LOCATION_HANDLER = 1
PLACEMARK_INSERTER_DESCRIPTION_HANDLER = 2
PLACEMARK_INSERTER_CATEGORIES_HANDLER = 3
PLACEMARK_INSERTER_TAGS_HANDLER = 4
PLACEMARK_INSERTER_INSERT_TAG_HANDLER = 5

PLACEMARK_EDITOR_HANDLER = 6
PLACEMARK_EDITOR_TAGS_HANDLER = 7
PLACEMARK_EDITOR_DESCRIPTION_HANDLER = 8
PLACEMARK_EDITOR_CATEGORIES_HANDLER = 9
PLACEMARK_EDITOR_LOCATION_HANDLER = 10
PLACEMARK_EDITOR_DELETE_HANDLER = 12
PLACEMARK_EDITOR_EDIT_MENU_HANDLER = 13
PLACEMARK_EDITOR_ADDRESS_HANDLER = 14
PLACEMARK_EDITOR_INSERT_TAG_HANDLER = 15