MAX_SHEET_LENGTH = 5
MAX_CATEGORIES_SHEET_LENGTH = 5

LEFT_ARROW = "←"
RIGHT_ARROW = "→"
BACK_ARROW = "↵"
ADD = "+"
EDIT = "✎"
DELETE = "❌"
SUBMIT = "✓︎"
CANCEL = "⨯"

MODE_SELECTOR_HANDLER = 0
NEW_TAGS_HANDLER = 1
APPROVED_PLACEMARKS_HANDLER = 2
ADD_CATEGORIES_AND_TAGS_HANDLER = 3
ADD_CATEGORY_HANDLER = 4
ADD_TAG_HANDLER = 5
APPROVED_PLACEMARKS_PLACEMARK_INFO_HANDLER = 6

INSERT_CATEGORY_AND_TAG_CATEGORIES_MENU_HANDLER = 7
INSERT_CATEGORY_AND_TAG_INSERT_CATEGORY_MENU_HANDLER = 8
INSERT_CATEGORY_AND_TAG_DELETE_CATEGORY_MENU_HANDLER = 9
INSERT_CATEGORY_AND_TAG_EDIT_CATEGORY_MENU_HANDLER = 10
INSERT_CATEGORY_AND_TAG_TAGS_MENU_HANDLER = 11
INSERT_CATEGORY_AND_TAG_INSERT_TAG_MENU_HANDLER = 12
INSERT_CATEGORY_AND_TAG_DELETE_TAG_MENU_HANDLER = 13
INSERT_CATEGORY_AND_TAG_TAG_MENU_HANDLER = 14
INSERT_CATEGORY_AND_TAG_EDIT_TAG_HANDLER = 15

NEW_TAGS_TAGS_MENU_HANDLER = 16
NEW_TAGS_TAG_MENU_HANDLER = 17
NEW_TAGS_TAG_EDIT_HANDLER = 18
NEW_TAGS_TAG_DELETE_HANDLER = 19
NEW_TAGS_TAG_APPROVE_HANDLER = 20

NEW_PLACEMARKS_HANDLER = 21
NEW_PLACEMARKS_PLACEMARK_MENU_HANDLER = 22
NEW_PLACEMARKS_PLACEMARK_DELETE_HANDLER = 23
NEW_PLACEMARKS_PLACEMARK_APPROVE_HANDLER = 24
NEW_PLACEMARKS_PLACEMARK_EDIT_HANDLER = 25
NEW_PLACEMARKS_PLACEMARK_EDIT_DESCRIPTION_HANDLER = 26
NEW_PLACEMARKS_PLACEMARK_EDIT_GEOTAG_HANDLER = 27
NEW_PLACEMARKS_PLACEMARK_EDIT_ADDRESS_HANDLER = 28
NEW_PLACEMARKS_PLACEMARK_NEW_TAGS_HANDLER = 29
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_HANDLER = 30
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_EDIT_HANDLER = 31
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_DELETE_HANDLER = 32
NEW_PLACEMARKS_PLACEMARK_NEW_TAG_APPROVE_HANDLER = 33
